add failing wasm test for `connected_components`
fails with:
`panicked at 'attempt to multiply with overflow', /rustc/e44fdf97929d1315add3b76208adf99e8299252d/src/libcore/num/mod.rs:3695:24`

this is I believe due to the overflow during `pow`
calculation